### ISSUE TITLE
本人webman小白一枚，没看懂这个怎么用的。按照文档集成了一下没起作用

### ISSUE THREAD

**Issue by xuellbcd** [krissss/webman-auth#3]
按照文档集成了一下，但是不登录的时候还是可以访问首页。是需要自己再额外写登录验证方法么？

**Comment by krissss** [comment]
应该是中间件没配置吧

你可以参考 [example](https://github.com/webman-tech/auth/blob/main/examples/multi-user/config/route.php) 中的路由配置的形式添加 WebmanTech\Auth\Middleware\Authentication::class

或者在全局中间件（config/middleware.php） 中添加

**Comment by xuellbcd** [comment]
> 应该是中间件没配置吧
> 
> 你可以参考 [example](https://github.com/webman-tech/auth/blob/main/examples/multi-user/config/route.php) 中的路由配置的形式添加 WebmanTech\Auth\Middleware\Authentication::class
> 
> 或者在全局中间件（config/middleware.php） 中添加

非常感谢！已经调通了
