### ISSUE TITLE
access-token 异常

### ISSUE THREAD

**Issue by yun3948** [krissss/webman-auth#4]
求助，现在有个access-token ，我本地使用访问是正常的，但是一起开发的人用这个token 就会401 
是有什么特别的验证嘛？

**Comment by yun3948** [comment]
另外，我想关闭token 认证应该如何操作呢？我在config/auth.php enable 改为false 就会报错

    "msg": "WebmanTech\\Auth\\AuthManager::getConfig(): Argument #1 ($name) must be of type string, null given, called in /www/wwwroot/api.nuys.com.cn/webman/vendor/webman-tech/auth/src/AuthManager.php on line 21",

**Comment by krissss** [comment]
> 求助，现在有个access-token ，我本地使用访问是正常的，但是一起开发的人用这个token 就会401 
> 是有什么特别的验证嘛？
> 

发一下具体的配置信息

**Comment by krissss** [comment]
> 另外，我想关闭token 认证应该如何操作呢？我在config/auth.php enable 改为false 就会报错
> 
>     "msg": "WebmanTech\\Auth\\AuthManager::getConfig(): Argument #1 ($name) must be of type string, null given, called in /www/wwwroot/api.nuys.com.cn/webman/vendor/webman-tech/auth/src/AuthManager.php on line 21",

auth.php里没有enable配置吧，app.php里的？

**Comment by yun3948** [comment]
对的。app 里面的 enable

**Comment by yun3948** [comment]
`
<?php
use WebmanTech\Auth\Authentication\FailureHandler\RedirectHandler;
use WebmanTech\Auth\Authentication\Method\SessionMethod;
use WebmanTech\Auth\Interfaces\IdentityRepositoryInterface;

return [
    // 默认 guard
    'default' => 'user',
    // 多 guard 配置
    'guards' => [
        'user' => [
            'class' => WebmanTech\Auth\Guard\Guard::class,
            'identityRepository' => function () {
                return new app\model\User();
            },
            'authenticationMethod' => function (IdentityRepositoryInterface $identityRepository) {
                return new WebmanTech\Auth\Authentication\Method\RequestMethod($identityRepository);
            },
            'authenticationFailureHandler' => function () {
              
                return new WebmanTech\Auth\Authentication\FailureHandler\ThrowExceptionHandler();
            },
        ],
     
       
    ]
];`

**Comment by yun3948** [comment]
这是auth 里面的配置

```
    'guards' => [
        'user' => [
            'class' => WebmanTech\Auth\Guard\Guard::class,
            'identityRepository' => function () {
                return new app\model\User();
            },
            'authenticationMethod' => function (IdentityRepositoryInterface $identityRepository) {
                return new WebmanTech\Auth\Authentication\Method\RequestMethod($identityRepository);
            },
            'authenticationFailureHandler' => function () {
              
                return new WebmanTech\Auth\Authentication\FailureHandler\ThrowExceptionHandler();
            },
        ],
     
       
    ]
```
我自己增加了一个前置的中间件 
···
    public function process(Request $request, callable $handler): Response
    {

        $controller = $request->controller;
        $action = $request->action;

        if (!$controller) {
            return $handler($request);
        }
        // 获取控制器鉴权信息
        $class = new \ReflectionClass($controller);
        $properties = $class->getDefaultProperties();
        $noNeedLogin = $properties['noNeedLogin'] ?? [];

        // 不需要登录
        if (in_array($action, $noNeedLogin)) {
             return $handler($request);
        }


        return parent::process($request, $handler);
    }
···

**Comment by krissss** [comment]
app.php里的enable关闭会导致整个auth的插件不起用的，这是webman的机制
然后报错是你又单独调用了auth里的方法，但是auth并没有被加载，尤其是auth.php配置并没有被载入，所以报错了

**Comment by krissss** [comment]
至于你这个为什么token你可以，别人不行，我暂时没想出啥原因，可能：
1.你们连的不是同一个数据库？所以token就不同
2.传access-token放的地方错了？或者名字写错了？
3.自己debug一下原因吧

**Comment by yun3948** [comment]
好的。大佬 能不能问下什么情况下会返回400 错误。他那边一直说不行。 我也很奇怪 囧

**Comment by krissss** [comment]
没有400吧，401是授权失败，就是你说的access-token不对

**Comment by yun3948** [comment]
他那边是这样的
![e304cd3558b3481e7a990951e33917f](https://user-images.githubusercontent.com/12403724/222906324-5fe566af-f9ea-4c53-afd9-310db2b8fb66.png)

**Comment by yun3948** [comment]
是我程序本身的问题吗

**Comment by krissss** [comment]
这个400是nginx拦截的应该，不过问题找到了：
get请求，会忽略body里的数据，所以取不到access-token

改成post，或者access-token放在query的param里

**Comment by yun3948** [comment]
好的。十分感谢...  没注意这个细节
